name: sree3app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_html: ^1.2.0
  http: ^0.12.2
  url_launcher: ^5.7.10
  woocommerce: ^0.9.7
  scoped_model: ^1.1.0
  cached_network_image: ^2.5.0
  shared_preferences: ^0.5.12+4
  provider: ^4.3.3
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  flutter_cache_manager: ^2.1.1
  dio: ^3.0.10
  fake_async: ^1.1.0
  intl: ^0.16.1
  date_range_picker: ^1.0.6
  auto_size_text: ^2.1.0
  share: ^0.6.5+4
  flutter_lock_screen: ^1.0.8
  local_auth: ^0.6.3+4
  cron: ^0.2.4
  esc_pos_printer: ^4.0.3
  qr_flutter: ^3.2.0
  ping_discover_network: ^0.2.0+1
  wifi: ^0.1.5
  typicons_flutter: ^0.4.2
  get: ^3.25.4
  flutter_secure_storage: ^3.3.5
  font_awesome_flutter: ^8.11.0
  localstorage: ^3.0.0+2





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/imge/1.jpg
    - assets/bg.jpg
    - assets/fingerprint.png
    - assets/imge/2.jpg
    - assets/imge/3.jpg
    - assets/imge/4.jpg
    - assets/imge/5.jpg
    - assets/imge/6.jpg
    - assets/imge/stem.jpg
    - assets/imge/logo.jpg
    - assets/imge/logo1.jpg
    - assets/imge/logo2.png
    - assets/imge/xbox.jpg
    - assets/imge/pubg.jpg
    - assets/imge/legend.jpg
    - assets/imge/roblox.jpg
    - assets/imge/freef.jpg
    - assets/imge/blotvip.jpg
    - assets/imge/lords.jpg
    - assets/imge/netindo.jpg
    - assets/imge/play.jpg
    - assets/imge/fifa.jpg
    - assets/imge/m1.jpeg
    - assets/imge/inter/frind.jpg
    - assets/imge/inter/go.jpg
    - assets/imge/inter/virgin.jpg
    - assets/imge/inter/lebara.jpg
    - assets/imge/inter/mobily.jpg
    - assets/imge/inter/zain.jpg
    - assets/imge/inter/stc.png
    - assets/imge/markit/almentor.jpg
    - assets/imge/markit/amazooon.jpg
    - assets/imge/markit/bysaif.jpg
    - assets/imge/markit/ebay.jpg
    - assets/imge/markit/google.jpg
    - assets/imge/markit/itunes.jpg
    - assets/imge/markit/kareem.jpg
    - assets/imge/markit/mrsol.jpg
    - assets/imge/markit/non.jpg
    - assets/imge/markit/razr.jpg
    - assets/imge/markit/tmmmt.jpg
    - assets/imge/cinma/kitab.jpg
    - assets/imge/cinma/neyflix.jpg
    - assets/imge/cinma/oeak.jpg
    - assets/imge/cinma/star.jpg
    - assets/imge/cinma/shahid.jpg
    - assets/imge/program/skype.jpg
    - assets/imge/program/facebook.jpg
    - assets/imge/program/mcafe.jpeg
    - assets/imge/program/office.jpeg
    - assets/imge/program/micro.jpeg
    - assets/imge/new/cinma.png
    - assets/imge/new/ishtrak.png
    - assets/imge/new/ituns.png
    - assets/imge/new/markit.png
    - assets/imge/new/play.png
    - assets/imge/new/program.png
    - assets/imge/new/rasid.png
    - assets/imge/logos/zain.png
    - assets/imge/logos/
    - assets/imge/logos/1.jpg
    - assets/imge/logos/printer.png
    - assets/imge/logos/revv-10.jpg
    - assets/imge/logos/header.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DIN Next LT W23
      fonts:
        - asset: assets/font/din-next-lt-w23-black.ttf
        - asset: assets/font/din-next-lt-w23-bold.ttf
        - asset: assets/font/din-next-lt-w23-heavy.ttf
          style: italic


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
